openapi: 3.1.0
x-stoplight:
  id: ljffzhgkd9n7o
info:
  title: video_host_api
  version: '3.0'
  description: 'フロントエンド: https://github.com/xpadev-net/video_host_frontend'
  summary: 自宅メディアサーバー用のAPI定義
  license:
    name: MIT
servers: []
paths:
  /auth:
    post:
      summary: 認証API
      operationId: post-auth
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: vljks9ltfjxl1
                  status:
                    type: string
                    x-stoplight:
                      id: 1dzhtnisun2ip
                required:
                  - code
                  - status
              examples:
                Example 1:
                  value:
                    code: '200'
                    status: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 8lc4pdiiebmyc
                  status:
                    type: string
                    x-stoplight:
                      id: ydpbyxrjjphib
                  message:
                    type: string
                    x-stoplight:
                      id: ks3g1r988lz8a
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: incorrect username or password
      description: ログイン認証用API
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  x-stoplight:
                    id: ks7juu8klgani
                password:
                  type: string
                  x-stoplight:
                    id: tfssh5q29tdxt
              required:
                - username
                - password
        description: ''
      x-internal: false
  /tryAuth:
    get:
      summary: トークン検証API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                required:
                  - code
                  - sutatus
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-tryAuth
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: ログイン用トークンが有効化の検証を行うAPI
  /logout:
    get:
      summary: ログアウトAPI
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                required:
                  - code
                  - sutatus
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-logout
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: ログイン用トークンを削除するAPI
    parameters: []
  '/movie/{movieUrl}':
    get:
      summary: 動画情報API
      tags: []
      responses:
        '200':
          description: |-
            OK

            prev/nextはnullable
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: object
                    x-stoplight:
                      id: q1ncsynfh5bt6
                    required:
                      - playlist
                      - movie
                      - source
                    properties:
                      playlist:
                        type: array
                        x-stoplight:
                          id: 3y78dv9wf1i10
                        items:
                          $ref: '#/components/schemas/Movie'
                          x-stoplight:
                            id: xyawopa50qjkh
                      movie:
                        $ref: '#/components/schemas/Movie'
                        x-stoplight:
                          id: zx1mttasuy85p
                      prev:
                        $ref: '#/components/schemas/Movie'
                        x-stoplight:
                          id: 9fcqlow0wh1v1
                        description: nullable
                      next:
                        $ref: '#/components/schemas/Movie'
                        x-stoplight:
                          id: 3rtfp97zrdqp6
                        description: nullable
                      source:
                        type: object
                        x-stoplight:
                          id: ti5rl3fplh7fi
                        required:
                          - http
                          - hls
                        properties:
                          http:
                            type: string
                            x-stoplight:
                              id: w52lz9g5f5vze
                          hls:
                            type: string
                            x-stoplight:
                              id: wynf7epuzcqpk
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      playlist:
                        - id: 0
                          url: string
                          seriesUrl: string
                          title: string
                          seriesTitle: string
                          duration: 0
                          addAt: 0
                      movie:
                        id: 0
                        url: string
                        seriesUrl: string
                        title: string
                        seriesTitle: string
                        duration: 0
                        addAt: 0
                      prev: null
                      next: null
                      source:
                        http: 'https://example.com/hoge.mp4'
                        hls: 'https://example.com/hoge.m3u8'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-movie
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: 再生ページで使用する動画情報を取得するAPI
    parameters:
      - schema:
          type: string
        name: movieUrl
        in: path
        required: true
  '/search/{query}':
    get:
      summary: 検索API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: object
                    x-stoplight:
                      id: etw0kzofcrr31
                    required:
                      - movies
                      - series
                    properties:
                      movies:
                        type: array
                        x-stoplight:
                          id: gk33hcmtybpts
                        items:
                          $ref: '#/components/schemas/Movie'
                          x-stoplight:
                            id: 2jjxgcqwx92i9
                      series:
                        type: array
                        x-stoplight:
                          id: 7kviby84gjvur
                        items:
                          x-stoplight:
                            id: kzkfb9fkonej7
                          type: object
                          properties:
                            seriesTitle:
                              type: string
                              x-stoplight:
                                id: 5zrjh5e3pm904
                            seriesUrl:
                              type: string
                              x-stoplight:
                                id: d8wgzzemogy5k
                          required:
                            - seriesTitle
                            - seriesUrl
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      movies:
                        - id: 0
                          url: string
                          seriesUrl: string
                          title: string
                          seriesTitle: string
                          duration: 0
                          addAt: 0
                      series:
                        - seriesTitle: string
                          seriesUrl: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
        '':
          description: ''
      operationId: get-search
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: 検索結果を返すAPI
    parameters:
      - schema:
          type: string
        name: query
        in: path
        required: true
  '/series/{seriesUrl}':
    get:
      summary: シリーズ取得API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: object
                    x-stoplight:
                      id: aoqifao2lrx2d
                    required:
                      - movies
                      - seriesTitle
                    properties:
                      movies:
                        type: array
                        x-stoplight:
                          id: 03tlntprc8lsu
                        items:
                          $ref: '#/components/schemas/Movie'
                          x-stoplight:
                            id: d4mo5q51lymh4
                      seriesTitle:
                        type: string
                        x-stoplight:
                          id: 9x02wo5qxif8l
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      movies:
                        - id: 0
                          url: string
                          seriesUrl: string
                          title: string
                          seriesTitle: string
                          duration: 0
                          addAt: 0
                      seriesTitle: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: u4in4qsdrjfzw
                  status:
                    type: string
                    x-stoplight:
                      id: yzagcak6onn6h
                  message:
                    type: string
                    x-stoplight:
                      id: nanj3mj7dg7dk
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '404'
                    status: fail
                    message: not found
        '':
          description: ''
      operationId: get-series
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: シリーズに含まれる動画一覧を取得するAPI
    parameters:
      - schema:
          type: string
        name: seriesUrl
        in: path
        required: true
  '/comments/{movieUrl}':
    get:
      summary: コメント取得API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: object
                    x-stoplight:
                      id: 2vbn4yybkjk6z
                    required:
                      - comments
                    properties:
                      comments:
                        type: array
                        x-stoplight:
                          id: mx57bqo0k2yjn
                        items:
                          $ref: '#/components/schemas/v1Comment'
                          x-stoplight:
                            id: qoow74ra3q580
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      comments:
                        - body: string
                          commands:
                            - string
                          id: string
                          isMyPost: true
                          isPremium: true
                          nicoruCount: 0
                          'no': 0
                          postedAt: string
                          score: 0
                          source: string
                          userId: string
                          vposMs: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-comments
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: 動画に紐付けられたコメントを取得するためのAPI
    parameters:
      - schema:
          type: string
        name: movieUrl
        in: path
        required: true
  '/suggest/{query}':
    get:
      summary: 検索サジェストAPI
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: array
                    x-stoplight:
                      id: 431gvhibkkiaw
                    items:
                      x-stoplight:
                        id: lrgocob2mza02
                      type: object
                      properties:
                        title:
                          type: string
                          x-stoplight:
                            id: 9v5f3zvsuw5jb
                      required:
                        - title
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      - title: hoge
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-suggest
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: 検索のサジェスト用API
    parameters:
      - schema:
          type: string
        name: query
        in: path
        required: true
  /recentUpdates:
    get:
      summary: 直近更新API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: y13z2jy2aktww
                  sutatus:
                    type: string
                    x-stoplight:
                      id: o3p14d1p5ypt4
                  data:
                    type: array
                    x-stoplight:
                      id: ho4hgc6svsu9f
                    items:
                      x-stoplight:
                        id: mhefjl79xgavi
                      type: object
                      properties:
                        seriesTitle:
                          type: string
                          x-stoplight:
                            id: q9dxy00uydr7i
                        seriesUrl:
                          type: string
                          x-stoplight:
                            id: 8ix0om2bvepga
                        movies:
                          type: array
                          x-stoplight:
                            id: 14rr7e9a1dwa2
                          items:
                            $ref: '#/components/schemas/Movie'
                            x-stoplight:
                              id: tjlcm6vwrgedp
                      required:
                        - seriesTitle
                        - seriesUrl
                        - movies
                required:
                  - code
                  - sutatus
                  - data
              examples:
                Example 1:
                  value:
                    code: '200'
                    sutatus: success
                    data:
                      - seriesTitle: string
                        seriesUrl: string
                        movies:
                          - id: 0
                            url: string
                            seriesUrl: string
                            title: string
                            seriesTitle: string
                            duration: 0
                            addAt: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: 17y4l3n3feh7a
                  status:
                    type: string
                    x-stoplight:
                      id: dupb4b9yyntw7
                  message:
                    type: string
                    x-stoplight:
                      id: f2hocagkywsfs
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '401'
                    status: fail
                    message: invalid token
      operationId: get-recentUpdates
      parameters:
        - schema:
            type: string
          in: cookie
          name: token
          description: 認証トークン
      description: 直近の更新を返すAPI
    parameters: []
  '/img/{movieUrl}':
    parameters:
      - schema:
          type: string
        name: movieUrl
        in: path
        required: true
    get:
      summary: サムネイルAPI
      tags: []
      responses:
        '200':
          description: webp画像のバイナリデータ
          content:
            image/webp:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    x-stoplight:
                      id: bnhcvbgz2sfk9
                  status:
                    type: string
                    x-stoplight:
                      id: qt178g4mmkw1p
                  message:
                    type: string
                    x-stoplight:
                      id: g618n6bhinbi2
                required:
                  - code
                  - status
                  - message
              examples:
                Example 1:
                  value:
                    code: '400'
                    status: fail
                    message: bad request
        '404':
          description: 404用画像のバイナリデータ
          content:
            image/png:
              schema:
                type: string
      operationId: get-img
      description: サムネイルの画像データを返すAPI
components:
  schemas:
    Movie:
      title: Movie
      x-stoplight:
        id: rnnfwni3kl1cs
      type: object
      properties:
        id:
          type: number
        url:
          type: string
          x-stoplight:
            id: rlda80os5yv3n
        seriesUrl:
          type: string
          x-stoplight:
            id: wbk7hj4hoktk4
        title:
          type: string
          x-stoplight:
            id: 9vy2he21m3x9v
        seriesTitle:
          type: string
          x-stoplight:
            id: tyvwxb8oocrv1
        duration:
          type: number
          x-stoplight:
            id: fu03g9las4pg8
        addAt:
          type: number
          x-stoplight:
            id: 1alxsu1p79qeq
    v1Comment:
      title: v1Comment
      x-stoplight:
        id: b6dbl37dv8tay
      type: object
      properties:
        body:
          type: string
          x-stoplight:
            id: 42bpx9q6if7hj
        commands:
          type: array
          x-stoplight:
            id: ydvptekn1mg3a
          items:
            x-stoplight:
              id: sgf21g1beml9x
            type: string
        id:
          type: string
          x-stoplight:
            id: f2ch10sb5mwts
        isMyPost:
          type: boolean
          x-stoplight:
            id: o9ykdnlkwpb42
        isPremium:
          type: boolean
          x-stoplight:
            id: yg19xmllt2ekk
        nicoruCount:
          type: number
          x-stoplight:
            id: zbr62e3p0v4w6
        'no':
          type: number
          x-stoplight:
            id: i508zspysikef
        postedAt:
          type: string
          x-stoplight:
            id: rm1bkiukykgrg
        score:
          type: number
          x-stoplight:
            id: 8shyvla3zwg1r
        source:
          type: string
          x-stoplight:
            id: 7xittyqoltxiw
        userId:
          type: string
          x-stoplight:
            id: hqtd6hfl7eqx0
        vposMs:
          type: number
          x-stoplight:
            id: 7b74bdl0p4x4x
      description: ''
  securitySchemes: {}
